CREATE TABLE IF NOT EXISTS medicos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  CRM VARCHAR(20) NOT NULL,
  UFCRM CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS pacientes (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  dataNascimento DATE NOT NULL,
  carteirinha VARCHAR(50) NOT NULL,
  cpf CHAR(11) NOT NULL
);
